stages:
  - ansible-lint
  - ansible-syntax-check

variables: 
  GIT_SSL_NO_VERIFY: "1"

ansible-lint:
  stage: ansible-lint
  image: luanngominh/ansible-lint:0.1
  script:
    - ansible-lint *.yml

workspace-syntax-chec:
  stage: ansible-syntax-check
  image: luanngominh/ansible-lint:0.1
  script:
    - ansible-playbook --synax-check workspace.yml
  only:
    - master
    - develop
    - /^feature/workspace(/.*$|$)/
    - /^hotfix/workspace(/.*$|$)/
