---
- hosts: influx
  become: true
  roles:
    - basic
    # - ntp
    # - influxdb

# Install checkMK cluster
- hosts: checkmk
  become: true
  roles:
    - basic
    # - ntp
    # more role such as DRDB, CoreSync and so on
    # - checkmk

