---
- hosts: all
  become: true
  vars_files:
    - roles/basic/vars/vars.yml
    - roles/workspace/vars/vars.yml
  vars:
    ansible_user: "{{ ansible_user }}"
    ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
  roles:
  - basic
  - workspace