---
- name: Copy alias some command
  copy:
    src: files/.meocon_profile
    dest: /etc/.meocon_profile

- name: Copy lzf
  copy:
    src: files/lzf
    dest: /etc/lzf

- name: Get profile
  command: cat /etc/profile
  register: profile

- name: Source alias file
  lineinfile:
    path: /etc/profile
    insertafter: EOF
    line: |
        source /etc/lzf
        source /etc/.meocon_profile
  when: profile.stdout.find("source /etc/lzf\nsource /etc/.meocon_profile") == -1