---
- name: Check Google APT file 
  command: test -f "{{ google_chrome_apt_file }}"
  register: google_apt_exists
  ignore_errors: True

- name: Add google chrome key
  apt_key: 
    id: "{{ chrome_apt_key_id }}"
    url: "{{ chrome_apt_key_url }}"
  when: google_apt_exists.rc == 1

- name: Add google chrome repository
  apt_repository:
    repo: "{{ chrome_repository }}"
    filename: "{{ google_chrome_apt_file }}"
  when: google_apt_exists.rc == 1 

- name: Install google chrome
  apt:
    name: google-chrome-stable 
    state: present
    update_cache: yes
