---
- name: Install docker dependencies
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "cron"
    - "gnupg2"
    - "software-properties-common"

- name: Add Docker's public PGP key to APT keyring
  apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_url }}"

- name: Configure Docker's upstream apt repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    update_cache: true

- name: Install docker
  apt:
    name: "docker-{{ docker_edition }}"
    state: present

- name: Add desktop user to group docker
  user:
    name: "{{ item }}"
    group: "docker"
    append: true
  