- name: Install tweak
  apt:
    name: tweak
    state: present

- name: Create dash-to-dock@micxgx.gmail.com folder
  file:
    path: "/home/{{ ansible_user }}/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com"
    state: directory
    mode: '751'
    owner: "{{ ansible_user }}"

- name: Install dash-to-dock
  unarchive:
    src: "{{ DASH_TO_DOCK }}"
    dest: "/home/{{ ansible_user }}/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com"
    remote_src: true
    owner: "{{ ansible_user }}"