---
- name: Check golang folder has not existed
  shell: test -d /usr/local/go
  register: go
  ignore_errors: yes

- name: Install golang
  unarchive:
    src: "{{ GO_LINK }}"
    dest: /usr/local
    remote_src: True
    mode: 0777
  when: go.rc != 0