---
- name: Checking node repository has existed
  command: test -f /etc/apt/sources.list.d/nodesource.list
  ignore_errors: true
  register: node

- name: Add apt key for nodesource
  apt_key:
    url: " {{ NODE_KEY }} "
  when: node.rc != 0

- name: Add repository for node source
  apt_repository:
    repo: "{{ item }}"
    filename: nodesource
  when: node.rc != 0
  with_items: "{{ NODE_REPO }}"

- name: Install nodejs
  apt :
    name: nodejs
    update_cache: yes
    state: present