---
- name: Check node is existed
  command: node -v
  register: node
  ignore_errors: yes

- name: Check npm is existed
  command: npm -v
  register: npm
  ignore_errors: yes

- name: Download node
  unarchive:
    src: "{{ NODE_FILE }}"
    dest: /usr/local
    remote_src: true
  when: node.rc != 0 or npm.rc != 0
  register: meow

# Get folder name from archive' name and rename to node
- name: Rename unarchive node folder
  command: "mv /usr/local/{{ NODE_FILE.split('/')[-1].split('.tar.xz')[0] }} /usr/local/node"
  ignore_errors: yes

- name: Create symbol link
  file:
    src: "/usr/local/node/bin/{{ item }}"
    state: link
    dest: "/usr/local/bin/{{ item }}"
  with_items:
  - npm
  - node
  - npx