---
- name: Checking node repository has existed
  command: test /etc/apt/sources.list.d/nodesource.list
  ignore_errors: true
  register: node

- name: Get add node repository script
  get_url: 
    url: "{{ NODE_REPO }}"
    dest: /tmp/node.sh
    mode: 700
  when: node.rc == 1

- name: Add node repository
  shell: /tmp/node.sh
  when: node.rc == 1

- name: Remove script
  file:
    path: /tmp/node.sh
    state: absent
  when: node.rc == 1

- name: Install nodejs
  apt:
    name: nodejs
    state: present

- name: Install npm
  apt:
    name: npm
    state: present