---
- name: Check telegram has not existed
  command: test -d /opt/Telegram
  register: tele
  ignore_errors: yes

- name: Install telegram
  unarchive:
    src: "{{ TELEGRAM_LINK }}"
    dest: /opt
    remote_src: True
  when: tele.rc != 0
