---
- name: Remove old version if any
  file:
    path: "/usr/local/bin/tf"
    state: absent
  ignore_errors: true

- name: Install terraform
  unarchive:
    src: "{{ TERRAFORM_LINK }}"
    dest: "/usr/local/bin"
    remote_src: true

- name: Rename terraform to tf
  file:
    src: "/usr/local/bin/terraform"
    dest: "/usr/local/bin/tf"
    state: hard
    mode: 0755

- name: Remove old terraform
  file:
    path: "/usr/local/bin/terraform"
    state: absent