---
- name: Add Visual's public PGP key to APT keyring
  apt_key:
    url: "{{ vscode_key_url }}"

- name: Config visual code upstream
  apt_repository:
    repo: "{{ vscode_repo }}"
    filename: vscode.list

- name: Install visual studio code
  apt:
    name: code
    state: latest
